blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/clones-ai/requests/discussions
    about: For usage questions, start a Discussion instead of filing a request.
